### ISSUE TITLE
Audio decoder for Spectrum tapes

### ISSUE THREAD

**Issue by tomas-nestorovic** [tomas-nestorovic/RIDE#31]
As there are few tools to extract tape blocks from sound files (e.g. just [ZXwav2tap](https://github.com/SilverGreen93/ZXwav2tap) and [Taper](https://github.com/Sirozha84/Taper), to name the only discoveries) it thus might be a good idea to add a native support for this functionality. As a starter, only raw sound files (WAV, VOC, IFF, etc.) should be supported. The application should analyze the sound and extract available valid blocks from it (with correct and incorrect checksum, and fragments). [Here](http://ramsoft.bbk.org.omegahg.com/tech/romload.zip) is a tutorial to getting started with the analysis. Apart of the basic functionality, these advanced features were [suggested](http://oldcomp.cz/viewtopic.php?f=37&t=7290&start=4):
- The implementation should visualize where leader tones (and other kinds of tones) were recognized. It ideally should also display the bits which were recognized from individual half-waves similarly as some oscilloscopes do when decoding RS232 and other kinds of signals (e.g. [this one](https://www.youtube.com/watch?v=MLtov8qjT_I&feature=youtu.be&t=840) by Rhode & Schwarz).
- The implementation should emphasize places which might be the cause of eventual error. For instance, it should be easy to display half-waves whose frequency is unexpected in a given context (e.g. out of tolerances for 0 and 1 bits).
- The implementation should allow manual adjustment of half-wave frequencies (and dynamically recalculate the checksum for non-fragment blocks). The motivation is that sometimes, the physical tape is stretched (e.g., due to the tooth of time) and it's necessary to slow down some part of the recording.
- The implementation should allow manual insertion/deletion of bits. The motivation is mainly the archiving: saving what can be saved. For instance, it's better to lose a part of a picture (which can be reconstructed by a skilled human archivist) than lose everything; the same holds for text. It's questionable whether the same approach can be used for code, but a human has at least a chance - the computer doesn't. If implemented, this feature would be brand new in the realm of decoding software!

**Comment by Yagoiglesias9** [comment]
https://user-images.githubusercontent.com/72929888/103173642-89bd2e80-485c-11eb-9da8-b27bee2e8b0b.mp4

**Comment by tomas-nestorovic** [comment]
Closed as no progress for years. This feature request is far beyond the priorities of the current app. May be reopened in the future when nothing else is to improve in the app.
