### ISSUE TITLE
Create new Release

### ISSUE THREAD

**Issue by gorgobacka** [tomas-nestorovic/RIDE#35]
Can you please create a new release? This is a really interesting project and since the release 1.4.6 you added several new features and improvements. But unfortunately, I can't compile it myself. (I'm using Linux, but it seems it works with Wine so far.)

**Comment by tomas-nestorovic** [comment]
Hi, thanks for using the app :-) I several times wanted to release a new version but haven't yet rigorously tested all the big changes in Issue #6 on a real floppy (and many small changes across the app), so I never felt "ready enough" to make a new version available publicly (just today, I committed a fix to a [critical bug](https://github.com/tomas-nestorovic/RIDE/commit/d6aa102433125a82db665d4e5e40628ab7d7b788) regarding a real FDD). Please give me yet 14 days, I unfortunately have many other things to solve for these days and months... :-/

PS: Thanks for testing the app under Linux :-)

**Comment by gorgobacka** [comment]
Yes, that's fine. Thanks for your response.

**Comment by tomas-nestorovic** [comment]
[New version](https://github.com/tomas-nestorovic/RIDE/releases/download/1.4.7/ride147.zip) is out, enjoy :-)

**Comment by gorgobacka** [comment]
Thanks!
