### ISSUE TITLE
Incorrectly recognized format: 5.25 Floppy, DS 1200kB 

### ISSUE THREAD

**Issue by gorgobacka** [tomas-nestorovic/RIDE#71]
I have the impression that the **5.25 Floppy, DS 1200kB** format is not correctly recognized. Can you please check?

Used version: 1.6.2

Example:
![5 25 Floppy, DS 1200kB](https://user-images.githubusercontent.com/10488441/138257654-7fa63205-2e8f-4b2a-bd32-c85af762968e.png)

**Comment by gorgobacka** [comment]
I check it again. Using my Wine configuration on Linux, the "Geometry"-Label is missing. But it's not a big deal for me. The information that I'm interested in is working fine and I can always use Windows in a VM, if I need to check something more in detail.
Maybe I will try different settings in Wine to solve it. I will share it, if I find something out.

**Comment by tomas-nestorovic** [comment]
Hi Thomas,

as for the missing "Geometry" label in the _Boot sector_ tab, I think I have solved the problem. Can you please try [this PropGrid](https://github.com/tomas-nestorovic/RIDE/files/7976975/PropGrid.zip) library? Just replace with it the existing library that comes with versions 1.6.2 or current 1.6.3, and please let me when you have time - thanks :-)

.

**Comment by gorgobacka** [comment]
I just tested with the current version (1.6.3) and it does not have the problem with the "Geometry" label anymore, even _without_ replacing the dll.
In 1.6.2 replacing the dll is needed to get rid of the issue.
