### ISSUE TITLE
Support for MBD image files of MB-02 disk interface

### ISSUE THREAD

**Issue by mborik** [tomas-nestorovic/RIDE#8]
Humble feature request to implementation of *.mbd image format of MB-02 disk interface which is pretty straightforward and [well documented](https://busy.speccy.cz/tvorba/mb02form.htm).

**Comment by tomas-nestorovic** [comment]
Hi Martin,
thanks for this suggestion and great documentation of MB-02! I leave the request unassigned at the moment as I don't currently have time and there's no documentation of RIDE's internals _yet_. I'd like to start writing a thorough documentation in the fall of this year, so when it's done you (or anyone) can read it and implement the DOS of their wish.
So please stay tuned :-)
Tomas

**Comment by mborik** [comment]
Great! Thanks for your effort in the implementation 😉👍

**Comment by tomas-nestorovic** [comment]
My pleasure! :-) In case of problems, don't hesitate to comment or create a new issue.

I already found one cosmetic issue - in the Boot Sector tab, the super-script numbers 1 and 2 are misinterpreted on 64-bit Windows (should be FAT¹ and FAT²)

![image](https://user-images.githubusercontent.com/37716001/71666596-e11be200-2d61-11ea-80b6-a4634534d11e.png)

Some other improvements will be added in 1H of 2020:
- Busy's MBD-Check to verify disk integrity (both image and real media),
- scanning of real media surface to make sure as many sectors fit in as possible on a problematic track,
- bootstrap composer (one of predefined _N_ actions) and viewer (in Z80 instructions).
